

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Adding lambda function code to s3 bucket..."
      - aws s3 mv deployment_package.zip s3://github-to-lambda-s3-test
      - aws lambda update-function-code --function-name testingFunction --s3-bucket github-to-lambda-s3-test --s3-key deployment_package.zip
      - echo "DONE!!"