

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - ls
      - pwd
      - echo "Zipping deployment package..."
      - cd lib
      - ls
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - ls
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

# So instead of updating the lambda function, we should generate an s3 bucket and upload the file there
# And then have the lambda function reference the s3 bucket.